In [4]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier


# CROSS validation is a techinque, where dataset is applied with different model to validate better accuracy .
#To identify which model provide better score .

In [6]:
from sklearn.datasets import load_digits   # to load predefined dataset in sklearn lib
df1=load_digits()
dir(df1) # list all parameters of digit dataset

['DESCR', 'data', 'images', 'target', 'target_names']

In [19]:
from sklearn.model_selection import train_test_split
X_train,X_test, Y_train,Y_test= train_test_split(df1.data,df1.target, test_size=0.3)

In [20]:
# Logistic Regreassion model

lr= LogisticRegression()
lr.fit(X_train,Y_train)
lr.score(X_test,Y_test)


0.9666666666666667

In [21]:
# Support vector Machine Model

sm=SVC()
sm.fit(X_train,Y_train)
sm.score(X_test,Y_test)


0.35

In [23]:
#Random frorest Regression model

RF1= RandomForestClassifier(n_estimators=20)
RF1.fit(X_train,Y_train)
RF1.score(X_test,Y_test)

0.9537037037037037

Kfold Cross Validation 
Basic Example
 

In [36]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)   # split based on 3 folds

In [38]:
#Example1
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [39]:
# Use Kfold for Digit dataset exmaple
# Creating method

def get_score1(model,X_train,X_test,Y_traain,Y_test):
    model.fit(X_train,Y_train)train,Y_tes
    return model.score(X_test,Y_test)

In [41]:
get_score1(sm,X_train,X_test,Y_train,Y_test)

0.35

In [40]:
# Kfold & stratisfied Kfold are same , where here samples are folded in 
# based on classification category in uniformwise

from sklearn.model_selection import StratifiedKFold
sk= StratifiedKFold(n_splits=3)

In [51]:
# Defining new list for each model

scores_logistic = []
scores_svm = []
scores_rf = []

for train_index,test_index in sk.split(df1.data,df1.target):
    X_train,X_test, Y_train,Y_test= df1.data[train_index],df1.data[test_index],\
                                    df1.target[train_index],df1.target[test_index]
        
    scores_logistic.append(get_score1(LogisticRegression(),X_train,X_test, Y_train,Y_test))
    scores_svm.append(get_score1(SVC(),X_train,X_test, Y_train,Y_test))
    scores_rf.append(get_score1(RandomForestClassifier(),X_train,X_test, Y_train,Y_test))
  
    


In [48]:
scores_logistic

[0.8953488372093024, 0.9499165275459098, 0.9093959731543624]

In [53]:
scores_svm

[0.39368770764119604, 0.41068447412353926, 0.4597315436241611]

In [54]:
scores_rf

[0.9036544850498339, 0.9115191986644408, 0.8959731543624161]

# cross_val_score function ( inbuilt function in Sklearn library), 
#cross_val_score uses stratifield kfold by default

from sklearn.model_selection import cross_val_score

In [56]:
#Logistic regression model performance using cross_val_score
cross_val_score(LogisticRegression(),df1.data,df1.target)


array([0.89534884, 0.94991653, 0.90939597])

# svm model performance using cross_val_score

In [57]:
cross_val_score(SVC(),df1.data,df1.target)  # check cell no. 53,57 provide same results

array([0.39368771, 0.41068447, 0.45973154])

# random forest performance using cross_val_score, Must to define Estimator parameter in RFS

In [59]:
cross_val_score(RandomForestClassifier(n_estimators=40),df1.data,df1.target)

array([0.94019934, 0.95325543, 0.93120805])

# Parameter tunning using k fold cross validation

In [61]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=5),df1.data, df1.target, cv=10)
np.average(scores1)

0.8765670684573037

In [66]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=10),df1.data, df1.target, cv=10)
print(scores1)
print("RFS_Score_AVG:",np.average(scores1))

[0.86486486 0.93989071 0.94475138 0.9        0.9273743  0.93296089
 0.9273743  0.95505618 0.9039548  0.89772727]
RFS_Score_AVG: 0.9193954708431994


In [67]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=20),df1.data, df1.target, cv=10)
np.average(scores1)

0.9410977719538419

In [68]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=30),df1.data, df1.target, cv=10)
np.average(scores1)

0.9456333143363042

In [73]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=50),df1.data, df1.target, cv=30)
np.average(scores1)

0.968192979232235

# # Observation :  Here we used cross_val_score to fine tune our random forest classifier and figured that having around  50 trees(n_estimator), CV=30  in random forest gives best result.